<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-icon_Lobby_person-add</name>
   <tag></tag>
   <elementGuidId>7ec3cd09-5c5d-42e1-820b-98e49c4f2e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-icon[name=&quot;person-add&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-icon[@name='person-add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>person-add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md hydrated</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>person add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;plt-tablet plt-cordova plt-desktop plt-hybrid md hydrated&quot;]/body[1]/app-root[1]/ion-app[@class=&quot;md ion-page hydrated&quot;]/ion-router-outlet[@class=&quot;hydrated&quot;]/app-navigation[@class=&quot;ion-page&quot;]/ion-tabs[1]/div[@class=&quot;tabs-inner&quot;]/ion-router-outlet[@class=&quot;hydrated&quot;]/app-room-list[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;md hydrated&quot;]/ion-fab[@class=&quot;md fab-horizontal-end fab-vertical-bottom hydrated&quot;]/ion-fab-list[@class=&quot;md fab-list-side-top hydrated fab-list-active&quot;]/ion-fab-button[@class=&quot;ion-color ion-color-secondary md fab-button-in-list ion-activatable ion-focusable hydrated fab-button-show ion-activated&quot;]/ion-icon[@class=&quot;md hydrated&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-icon[@name='person-add']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-fab-button[2]/ion-icon</value>
   </webElementXpaths>
</WebElementEntity>
